### ISSUE TITLE
Python script fails.

### ISSUE THREAD

**Issue by marcusramberg** [yaegashi/ansible-role-rundeckres#1]
Hi.

I'm trying to use this role, but I get this error:

 marcusr@foobar2 $ python files/rundeckres.py
  File "files/rundeckres.py", line 60
    c = {k: v for k, v in b.items() if v.strip() != ''}
                ^
SyntaxError: invalid syntax

Does it require a fairly recent python version?

**Comment by yaegashi** [comment]
Fixed in v0.3.

**Comment by marcusramberg** [comment]
Thanks!
